#简单的尝试
orthlistgraph.out : orthlistgraph.o
	gcc -o orthlistgraph.o orthlistgraph.out 

orthlistgraph.o : orthlistgraph.c
	gcc -c -Wall orthlistgraph.c  breadthfirstsearch.h

clean:
	rm orthlistgraph.o
